POST http://localhost:3000/users
Content-Type : application/json

{
    "firstName" : "Koola",
    "lastName" :"John",
    "email" : "kola@gmail.com",
    "password" : "Password123#"

}
POST http://localhost:3000/users/create-many
Content-Type: application/json

{
"users": [
    {
      "firstName": "Mark",
      "lastName": "Doe",
      "email": "tokolam@doe.com",
      "password": "Password123#"
    },
    {
      "firstName": "Tom",
      "lastName": "Doe",
      "email": "tom@doe.com",
      "password": "Password123#"
    },{
      "firstName": "Kola",
      "lastName": "Ahmed",
      "email": "tokolam@doe.com",
      "password": "Password123#"
    }
  ]
}

